### ISSUE TITLE
Example in README doesn't work

### ISSUE THREAD

**Issue by austencollins** [serverless-components/aws-cloudformation#2]
Tried following the readme and ran into:

```

  error:
  Error: Invalid inputs; template and stackName are required.
    at AwsCloudFormation.default (/Users/austen/.serverless/components/registry/npm/@serverless/aws-cloudformation@1.0.0/node_modules/@serverless/aws-cloudformation/serverless.js:39:13)
    at defaultFunction (/Users/austen/.serverless/components/registry/npm/@serverless/aws-cloudformation@1.0.0/node_modules/@serverless/core/src/Component.js:36:27)
    at fn (/usr/local/lib/node_modules/serverless/node_modules/@serverless/template/utils.js:276:47)

  6s › myStack › Error: Invalid inputs; template and stackName are required.
```

**Comment by eahefnawy** [comment]
Thanks @ac360 .. updated the README

**Comment by ztc212** [comment]
> Tried following the readme and ran into:
> 
> ```
> 
>   error:
>   Error: Invalid inputs; template and stackName are required.
>     at AwsCloudFormation.default (/Users/austen/.serverless/components/registry/npm/@serverless/aws-cloudformation@1.0.0/node_modules/@serverless/aws-cloudformation/serverless.js:39:13)
>     at defaultFunction (/Users/austen/.serverless/components/registry/npm/@serverless/aws-cloudformation@1.0.0/node_modules/@serverless/core/src/Component.js:36:27)
>     at fn (/usr/local/lib/node_modules/serverless/node_modules/@serverless/template/utils.js:276:47)
> 
>   6s › myStack › Error: Invalid inputs; template and stackName are required.
> ```

I've been testing this out since yesterday and the example in readme (as is) still gives the same error unless I move the CloudFormation code to separate file. e.g. this works:
```
CloudFormationStack:
  component: '@serverless/aws-cloudformation'
  inputs:
    stackName: myStackName
    template: ./template.yml
```
Also, the functionality listed in the [@serverless/components](https://github.com/serverless/components) readme doesn't seem to work?
- `${env.TABLE}`
- `env:`
   `  dbName: ${database.name}`
